//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JirafeForPolina.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Children
    {
        public int Id { get; set; }
        public string Firstname { get; set; }
        public string Name { get; set; }
        public string Middlename { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int IdUser { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual User User { get; set; }
    }
}
